WITH INFO AS (
    SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, B.PRICE * SUM(BS.SALES) AS `TOTAL_SALES`
FROM BOOK AS B
INNER JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
INNER JOIN BOOK_SALES AS BS ON B.BOOK_ID = BS.BOOK_ID
WHERE BS.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, B.PRICE
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC)
SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(TOTAL_SALES) AS `TOTAL_SALES`
FROM INFO
GROUP BY AUTHOR_ID, AUTHOR_NAME, CATEGORY;