WITH LENT AS (
    SELECT CAR_ID AS LENT_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE)
SELECT CAR_ID,
    CASE 
        WHEN L.LENT_ID IS NULL THEN '대여 가능'
        ELSE '대여중'
    END AS `AVAILABILITY`
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
LEFT JOIN LENT L ON C.CAR_ID = L.LENT_ID
GROUP BY C.CAR_ID
ORDER BY C.CAR_ID DESC;