WITH TARGET AS (
    SELECT CAR_ID, COUNT(*) AS TOTAL_CNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
)

SELECT MONTH(HIS.START_DATE), HIS.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY HIS INNER JOIN TARGET ON HIS.CAR_ID = TARGET.CAR_ID
WHERE TARGET.TOTAL_CNT >= 5 and START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH(HIS.START_DATE), HIS.CAR_ID
ORDER BY MONTH(HIS.START_DATE)  ASC , HIS.CAR_ID DESC;

