WITH MAX_FISH AS (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LEN
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)

SELECT FI.ID, FNI.FISH_NAME, FI.LENGTH
FROM FISH_INFO AS FI
INNER JOIN FISH_NAME_INFO AS FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
INNER JOIN MAX_FISH AS MF ON FI.FISH_TYPE = MF.FISH_TYPE AND FI.LENGTH = MF.MAX_LEN
ORDER BY FI.ID ASC;