WITH MF AS (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
), MFL AS (
    SELECT FI.ID, FI.FISH_TYPE, FI.LENGTH
    FROM FISH_INFO AS FI JOIN MF ON MF.FISH_TYPE = FI.FISH_TYPE AND MF.MAX_LENGTH = FI.LENGTH
)

SELECT MFL.ID, FNI.FISH_NAME, MFL.LENGTH
FROM FISH_NAME_INFO FNI
LEFT JOIN MFL ON FNI.FISH_TYPE = MFL.FISH_TYPE
ORDER BY MFL.ID ASC;