WITH AI AS (

    SELECT FISH_TYPE,
        AVG(IFNULL(LENGTH, 10)) AS AVG_LENGTH,
        COUNT(FISH_TYPE) AS FISH_COUNT,
        MAX(IFNULL(LENGTH, 10)) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)

SELECT FISH_COUNT, MAX_LENGTH, FISH_TYPE
FROM AI
WHERE AVG_LENGTH >= 33
ORDER BY FISH_TYPE;